apiVersion: apps/v1
kind: Deployment
metadata:
  name: demogat-yaml
spec:
  selector:
    matchLabels:
      app: gato
  template:
    metadata:
      labels:
        app: gato
    spec:
      containers:
        - name: contenedor-gato
          image: tomcat:11.0.0-M20
      